# Example: Using forge-standard library
#
# This demonstrates loading modules from a package installed
# to forge home (~/.local/share/forge/node_modules/)

dependencies:
  # For local development, use relative path for portability
  # For production use: git+ssh://git@github.com/jdillon/forge-standard.git#release
  - file:../../../forge-standard

modules:
  # Load the hello module from forge-standard
  # Package name comes from forge-standard/package.json: "@planet57/forge-standard"
  - "@planet57/forge-standard/hello"
